<?php

class EnglundProducts
{

	public $product_type_list;
	public $product_type_list_solo;


	public $department;

	function getProductTypeList()
	{

		if(!isset($this->department)){
			$this->department = '';
		}
		print 'searching by Department code::::';
		print_r($this->department);
		print '<br/><br/>';
		//build array of product and product types
		//This will identify a particular product as a parent or child


//Main query-   this is the main query of items to be included in the catalog (have a catalog page# assigned or have page# of "ADD")
// The complication is that the children items have a page number....but the parent items are assigned a page number of "REP"
// I can't simply select all the items with page# of "REP" because I only want to include the REP items ("parents") that coincide with the children that have page numbers.  So run two queries and stack them.
//Part 1=  regular and children items- these items have a page number or are ADD items.  Representative items have catalog page# of REP and are therefore excluded from Part 1.
//Part 2= parent items-  this list is generated by making a list of children items that have a page number or are ADD items and then grouping these children by the representative item number.  List is limited to items that have a representative item (this excludes the "regular" items)

//		$query =
//				'SELECT dw_item.dwin_display_item_number AS item_number, view_representative_items.dwin_display_item_number AS cluster,
//       if(sgir_item_number IS NULL,"Regular", if(dw_item.dwin_display_item_number=view_representative_items.dwin_display_item_number,"parent","child")) AS item_type
//       FROM dw_item
//	   INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'"
//	   INNER JOIN `IN` ON `dw_item`.`dwin_item_number`=`IN`.`in_item_number` AND `dw_item`.`dwin_store`=`IN`.`in_store` AND `dw_item`.`dwin_store`=1 AND `IN`.`in_store`=1
//
//
//	   LEFT JOIN SGIR ON dw_item.dwin_item_number = SGIR.sgir_item_number AND dw_item.dwin_store=1
//       LEFT JOIN view_representative_items ON SGIR.sgir_representative_item = view_representative_items.dwin_item_number
//       LEFT JOIN dw_item AS dw_item_1 ON view_representative_items.dwin_item_number = dw_item_1.dwin_item_number AND dw_item_1.dwin_item_number=1
//	   WHERE (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD")
//
//       UNION ALL
//
//       SELECT `dw_item_1`.`dwin_display_item_number` AS item_number, `SGIR`.`sgir_representative_item` AS cluster, "parent" AS item_type
//     FROM `dw_item`
//     INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'"
//     INNER JOIN `IN` ON `dw_item`.`dwin_store` = `IN`.`in_store` AND `dw_item`.`dwin_item_number` = `IN`.`in_item_number`
//     INNER JOIN `SGIR` ON `IN`.`in_item_number` = `SGIR`.`sgir_item_number`
//     INNER JOIN `view_representative_items` ON `SGIR`.`sgir_representative_item` = `view_representative_items`.`dwin_item_number`
//     INNER JOIN `dw_item` AS `dw_item_1` ON `view_representative_items`.`dwin_display_item_number` = `dw_item_1`.`dwin_item_number`
//     WHERE (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD") AND `dw_item`.`dwin_store`="1" AND `dw_item_1`.`dwin_store`="1"
//     GROUP BY `dw_item_1`.`dwin_display_item_number`, `SGIR`.`sgir_representative_item`, "parent"
//     HAVING `SGIR`.`sgir_representative_item`<>""   ';


		//jeremy's from 8/29 - set 1
		$query =

				'SELECT dw_item.dwin_display_item_number AS item_number, view_representative_items.dwin_display_item_number AS cluster,
       if(sgir_item_number IS NULL,"Regular", if(dw_item.dwin_display_item_number=view_representative_items.dwin_display_item_number,"parent","child")) AS item_type
       FROM dw_item
       INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'"
       INNER JOIN `IN` ON `dw_item`.`dwin_item_number`=`IN`.`in_item_number` AND `dw_item`.`dwin_store`=`IN`.`in_store` AND `dw_item`.`dwin_store`=1 AND `IN`.`in_store`=1 AND (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD")
       LEFT JOIN SGIR ON dw_item.dwin_item_number = SGIR.sgir_item_number AND dw_item.dwin_store=1
       LEFT JOIN view_representative_items ON SGIR.sgir_representative_item = view_representative_items.dwin_item_number
       LEFT JOIN dw_item AS dw_item_1 ON view_representative_items.dwin_item_number = dw_item_1.dwin_item_number AND dw_item_1.dwin_item_number=1
      
       UNION ALL
 
       SELECT `dw_item_1`.`dwin_display_item_number` AS item_number, `SGIR`.`sgir_representative_item` AS cluster, "parent" AS item_type
     FROM `dw_item`
     INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'"
     INNER JOIN `IN` ON `dw_item`.`dwin_store` = `IN`.`in_store` AND `dw_item`.`dwin_item_number` = `IN`.`in_item_number` AND (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD") AND `dw_item`.`dwin_store`="1"
     INNER JOIN `SGIR` ON `IN`.`in_item_number` = `SGIR`.`sgir_item_number` AND `SGIR`.`sgir_representative_item`<>""
     INNER JOIN `view_representative_items` ON `SGIR`.`sgir_representative_item` = `view_representative_items`.`dwin_item_number`
     INNER JOIN `dw_item` AS `dw_item_1` ON `view_representative_items`.`dwin_display_item_number` = `dw_item_1`.`dwin_item_number` AND `dw_item_1`.`dwin_store`="1"
     GROUP BY `dw_item_1`.`dwin_display_item_number`, `SGIR`.`sgir_representative_item`, "parent"
      ';


		//jeremy's from 8/29-set 2
//		$query =
//				'SELECT dw_item.dwin_display_item_number AS item_number, view_representative_items.dwin_display_item_number AS cluster,
//       if(sgir_item_number IS NULL,"Regular", if(dw_item.dwin_display_item_number=view_representative_items.dwin_display_item_number,"parent","child")) AS item_type
//       FROM dw_item
//       INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'" AND (`dw_item`.`dwin_display_item_number`="SEA420203-1" OR `dw_item`.`dwin_display_item_number`="SEA420209-1" OR `dw_item`.`dwin_display_item_number`="SEA420201-1" OR `dw_item`.`dwin_display_item_number`="SEA420204-1" OR `dw_item`.`dwin_display_item_number`="SEA420208-1" OR `dw_item`.`dwin_display_item_number`="SEA420202-1")
//       INNER JOIN `IN` ON `dw_item`.`dwin_item_number`=`IN`.`in_item_number` AND `dw_item`.`dwin_store`=`IN`.`in_store` AND `dw_item`.`dwin_store`=1 AND `IN`.`in_store`=1 AND (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD")
//       LEFT JOIN SGIR ON dw_item.dwin_item_number = SGIR.sgir_item_number AND dw_item.dwin_store=1
//       LEFT JOIN view_representative_items ON SGIR.sgir_representative_item = view_representative_items.dwin_item_number
//       LEFT JOIN dw_item AS dw_item_1 ON view_representative_items.dwin_item_number = dw_item_1.dwin_item_number AND dw_item_1.dwin_item_number=1
//
//       UNION ALL
//
//       SELECT `dw_item_1`.`dwin_display_item_number` AS item_number, `SGIR`.`sgir_representative_item` AS cluster, "parent" AS item_type
//     FROM `dw_item`
//     INNER JOIN `IN_EXT` ON `dw_item`.`dwin_item_number`=`IN_EXT`.`in_item_number` AND `dw_item`.`dwin_store`=`IN_EXT`.`in_store` AND `dwin_store`=1 AND `IN_EXT`.`inext_ext_35`="'.$this->department.'"
//     INNER JOIN `IN` ON `dw_item`.`dwin_store` = `IN`.`in_store` AND `dw_item`.`dwin_item_number` = `IN`.`in_item_number` AND (`IN`.`in_catalogue_page` Between "0000" And "2000" Or `IN`.`in_catalogue_page`="ADD") AND `dw_item`.`dwin_store`="1"
//     INNER JOIN `SGIR` ON `IN`.`in_item_number` = `SGIR`.`sgir_item_number` AND `SGIR`.`sgir_representative_item`<>""
//     INNER JOIN `view_representative_items` ON `SGIR`.`sgir_representative_item` = `view_representative_items`.`dwin_item_number`
//     INNER JOIN `dw_item` AS `dw_item_1` ON `view_representative_items`.`dwin_display_item_number` = `dw_item_1`.`dwin_item_number` AND `dw_item_1`.`dwin_store`="1"  AND `dw_item_1`.`dwin_display_item_number`="SEA42020"
//     GROUP BY `dw_item_1`.`dwin_display_item_number`, `SGIR`.`sgir_representative_item`, "parent"
//      ';


		//junk
		//AND (`dw_item`.`dwin_display_item_number`="SEA42020" OR `dw_item`.`dwin_display_item_number`="SEA420203-1" OR `dw_item`.`dwin_display_item_number`="SEA420209-1" OR `dw_item`.`dwin_display_item_number`="SEA420201-1" OR `dw_item`.`dwin_display_item_number`="SEA420204-1" OR `dw_item`.`dwin_display_item_number`="SEA420208-1" OR `dw_item`.`dwin_display_item_number`="SEA420202-1")



//		if($this->department !=''){
//			$query .= 'AND `view_dw_department`.`dwde_department` = %s  ';

//		}
//print_r($query);
		$list = DB::query($query,$this->department);
//		print '<br/>-------list-------<br/>';
//print_r($list);
//$list2 = array_unique($list);
//
//		print '<br/>-------uniquelist-------<br/>';
//		print_r($list2);


		foreach ($list as $row) {
//			$this->product_type_list[$row['item_number']] = array(
//					'item_number'=> $row['item_number'],
//					'cluster'=> $row['cluster'],
//					'item_type'=> $row['item_type'],
//
//			);

			if (is_null($row['cluster'])) {
				//regular product (not a parent/child)
				//print '<br/>im null:.'.$row['item_number'];
				$this->product_type_list_solo[$row['item_number']] = array(
						'item_number' => $row['item_number'],
						'cluster' => $row['cluster'],
						'item_type' => $row['item_type'],

				);


			} else {
				//either a parent or child
				$this->product_type_list[$row['item_number']] = array(
						'item_number' => $row['item_number'],
						'cluster' => $row['cluster'],
						'item_type' => $row['item_type'],

				);


			}


		}

	}

}




